spring:
  config:
    import: optional:file:/run/secrets/

relution:
  system:
    admin:
      password: ${system_admin_password}
      email: %SYSTEM_ADMIN_EMAIL%
  server:
    externalURL: %EXT_HOSTNAME_URL%
  database:
    type: postgresql
    # Adjust hostname in the url if the database runs outside docker compose
    url: jdbc:postgresql://database:5432/relution?currentSchema=public
    username: relution
    password: ${postgres_password}
